# model path
BASE_GPT_MODEL_PATH = "YOUR_MODEL_PATH"
LARGE_GPT_MODEL_PATH = "YOUR_MODEL_PATH"
BLOOM_MODEL_PATH = "YOUR_MODEL_PATH"

# tokenizer path
GPT_TOKENIZER_PATH = "YOUR_TOKENIZER_PATH"
BLOOM_TOKENIZER_PATH = "YOUR_TOKENIZER_PATH"

# Vector DB path
VDB_PATH = "YOUR_VDB_PATH"
VDB_MODLE = "YOUR_VDB_MODEL"  # from hugging face
VDB_HUGGING_FACE_API = "YOUR_API"
VDB_COLLECTION_NAME = "YOUR_COLLECTION_NAME"